name: CI de Calculadora con Jest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Permisos
        run: chmod +x ./node_modules/.bin/jest

      - name: Ejecutar pruebas Jest
        run: npm test

      - name: Simular Despliegue Exitoso
        run: echo "🚀 Deploy exitoso"
